name: Black CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9' 
    
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Run the 'black' code formatter on all of the Python files in root and subdirectories. 
      - name: Test this application 
        run: |
          find . -name "*.py" -exec black --check {} \; 
          EXIT_CODE=$?
          find . -name "*.py" -exec black {} \; 
          if [ "$EXIT_CODE" -eq 1 ]; then 
            echo "Black formatted text... Do better." 
            exit 1
          fi
